### ISSUE TITLE
TODO/FIXME Count 16

### ISSUE THREAD

**Issue by mattcollier** [digitalbazaar/bedrock-authn-token#19]
- [ ] FIXME: create custom instance to just set these global options once
       Commit: (5064688) Add `totp.window` config option.
       File:  [lib/index.js:427](https://github.com/digitalbazaar/bedrock-authn-token/blob/master/lib/index.js#L427)
       David I. Lehn commented 3 months ago

  - [ ] TODO: implement challenge check
       Commit: (b4f9a3c) Add core files.
       File:  [lib/index.js:403](https://github.com/digitalbazaar/bedrock-authn-token/blob/master/lib/index.js#L403)
       Dave Longley commented 2 years ago

  - [ ] TODO: handle the case where an email address is associated with more
       Commit: (9084453) Include token information in verification response.
       File:  [lib/index.js:362](https://github.com/digitalbazaar/bedrock-authn-token/blob/master/lib/index.js#L362)
       Dave Longley commented 4 months ago

  - [x] FIXME: this code is problematic if `account` is not set (likely being
       Commit: (83f6b06) Add FIXMEs.
       File:  [lib/index.js:349](https://github.com/digitalbazaar/bedrock-authn-token/blob/master/lib/index.js#L349)
       Dave Longley commented 3 months ago

  - [ ] TODO: could call `api.get()` here if not for the need for
       Commit: (02e219a) Fix typos.
       File:  [lib/index.js:347](https://github.com/digitalbazaar/bedrock-authn-token/blob/master/lib/index.js#L347)
       Dave Longley commented 2 years ago

  - [ ] FIXME: BedrockError
       Commit: (ad47995) TOTP updates.
       File:  [lib/index.js:331](https://github.com/digitalbazaar/bedrock-authn-token/blob/master/lib/index.js#L331)
       David I. Lehn commented 3 months ago

  - [ ] TODO: make these bedrock.config options
       Commit: (ed5c2bb) Add todo.
       File:  [lib/index.js:187](https://github.com/digitalbazaar/bedrock-authn-token/blob/master/lib/index.js#L187)
       David I. Lehn commented 3 months ago

  - [ ] FIXME: use readable email and service name
       Commit: (ed5c2bb) Add todo.
       File:  [lib/index.js:183](https://github.com/digitalbazaar/bedrock-authn-token/blob/master/lib/index.js#L183)
       David I. Lehn commented 3 months ago

  - [ ] FIXME: save params in token and use explicitly? (algorithm, digits, step)
       Commit: (48d09a0) TOTP Updates.
       File:  [lib/index.js:174](https://github.com/digitalbazaar/bedrock-authn-token/blob/master/lib/index.js#L174)
       David I. Lehn commented 3 months ago

  - [ ] TODO: implement
       Commit: (b4f9a3c) Add core files.
       File:  [lib/index.js:144](https://github.com/digitalbazaar/bedrock-authn-token/blob/master/lib/index.js#L144)
       Dave Longley commented 2 years ago

  - [ ] FIXME: may need to allow up to N tokens, one per `clientId` if
       Commit: (9f9168f) Add ability to include `clientId` in nonce/challenge tokens.
       File:  [lib/index.js:105](https://github.com/digitalbazaar/bedrock-authn-token/blob/master/lib/index.js#L105)
       Dave Longley commented 5 months ago

  - [ ] FIXME: this code is problematic if `account` is not set (likely being
       Commit: (ad2e9ed) Add FIXME and fix style.
       File:  [lib/index.js:85](https://github.com/digitalbazaar/bedrock-authn-token/blob/master/lib/index.js#L85)
       Dave Longley commented 3 months ago

  - [ ] TODO: implement getting/removing token clients
       Commit: (bbea6e0) Add code to check token dependencies (for multifactor flows).
       File:  [lib/clients.js:190](https://github.com/digitalbazaar/bedrock-authn-token/blob/master/lib/clients.js#L190)
       Dave Longley commented 4 months ago

  - [ ] TODO: add more information associated with the client to allow the user
       Commit: (bbea6e0) Add code to check token dependencies (for multifactor flows).
       File:  [lib/clients.js:95](https://github.com/digitalbazaar/bedrock-authn-token/blob/master/lib/clients.js#L95)
       Dave Longley commented 4 months ago

  - [x] FIXME: this code is problematic if `account` is not set (likely being
       Commit: (83f6b06) Add FIXMEs.
       File:  [lib/clients.js:80](https://github.com/digitalbazaar/bedrock-authn-token/blob/master/lib/clients.js#L80)
       Dave Longley commented 3 months ago

  - [ ] TODO: verify challenge by calling token-specific API
       Commit: (3232edf) Support verification of hash-based challenges or clear ones.
       File:  [lib/index.js:440](https://github.com/digitalbazaar/bedrock-authn-token/blob/master/lib/index.js#L440)
       Dave Longley commented 4 months ago

**Comment by dlongley** [comment]
Some of these are addressed by #42.

**Comment by dlongley** [comment]
Closing as addressed / addressed by #54 or other single issues now cover remaining items.
